### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by zacsimile**

### CODE REVIEW

**Comment by zacsimile** [comment]
Not really sure why this test is failing. Doesn't seem to be related to the documentation edits.

**Review by AdvancedImagingUTSW — COMMENTED** [review]
Changes to the documentation look great. Will transition to the tests now.

**Comment by AdvancedImagingUTSW** [comment]
Looking at the tests...

`TestCameraSettingController.test_update_fov` passes on my personal computer. I'll quickly check on a Windows machine.

**Comment by AdvancedImagingUTSW** [comment]
Tests pass on Windows machine. Rerunning the GitHub Action, and if it passes, will merge.

**Comment by AdvancedImagingUTSW** [comment]
You're good @zacsimile

**Review by AdvancedImagingUTSW — APPROVED** [review]

**Pull request merged**
