### PR TITLE
622 write fails when we hit maximum disk space

### LINKED ISSUE #622: Write fails when we hit maximum disk space
I know we check for disk space before starting an acquisition (#507), but it seems this is insufficient. An example of where this approach fails is copying data to the saving directory while the acquisition is running. In this case, the available space shrinks mid-acquisition with no alert. I think we need to wrap the `write` call in a `try`/`except` block and gracefully close when we are out of disk space. Unfortunately, closing requires a slight amount of disk space, so this may fail too. Still not quite sure how to handle this, but I think it's work just giving the `try`/`except` a go. Perhaps another approach would be to "look ahead" one frame and cut off acquisition early. But, this sort of prediction may get us into trouble in the exact same example I provided above.

```
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 201, in h5py._objects.ObjectID.__dealloc__
OSError: [Errno 28] Driver write request failed (file write failed: time = Tue Sep 19 18:46:15 2023
, filename = 'D:\kartik\091923braintest\NA\cfos-AF647_autofluorescence488\2023-09-19\Cell_001\CH00_000000.h5', file descriptor = 4, errno = 28, error message = 'No space left on device', buf = 00000195AF3D3798, total write size = 4096, bytes this sub-write = 4096, bytes actually written = 18446744073709551615, offset = 146627814192)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 201, in h5py._objects.ObjectID.__dealloc__
OSError: [Errno 28] Driver write request failed (file write failed: time = Tue Sep 19 18:46:15 2023
, filename = 'D:\kartik\091923braintest\NA\cfos-AF647_autofluorescence488\2023-09-19\Cell_001\CH00_000000.h5', file descriptor = 4, errno = 28, error message = 'No space left on device', buf = 00000195AF3D3798, total write size = 4096, bytes this sub-write = 4096, bytes actually written = 18446744073709551615, offset = 146627814192)
Exception in thread z-stack Data:
Traceback (most recent call last):
  File "c:\users\dean-lab\desktop\aslm\src\aslm\model\features\image_writer.py", line 251, in save_image
    self.data_source.write(
  File "c:\users\dean-lab\desktop\aslm\src\aslm\model\data_sources\bdv_data_source.py", line 143, in write
    self.image[dataset_name][zs, ...] = data[::dy, ::dx].astype(np.int16)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\site-packages\h5py\_hl\dataset.py", line 999, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 283, in h5py.h5d.DatasetID.write
  File "h5py\_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: [Errno 28] Can't write data (file write failed: time = Tue Sep 19 18:46:15 2023
, filename = 'D:\kartik\091923braintest\NA\cfos-AF647_autofluorescence488\2023-09-19\Cell_001\CH00_000000.h5', file descriptor = 4, errno = 28, error message = 'No space left on device', buf = 00000195AF3D1778, total write size = 4096, bytes this sub-write = 4096, bytes actually written = 18446744073709551615, offset = 146628789040)

Traceback (most recent call last):
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\dean-lab\desktop\aslm\src\aslm\model\model.py", line 775, in run_data_process
    data_func(frame_ids)
  File "c:\users\dean-lab\desktop\aslm\src\aslm\model\features\image_writer.py", line 283, in save_image
    self.close()
  File "c:\users\dean-lab\desktop\aslm\src\aslm\model\features\image_writer.py", line 346, in close
    self.data_source.close()
  File "c:\users\dean-lab\desktop\aslm\src\aslm\model\data_sources\bdv_data_source.py", line 259, in close
    self.image.close()
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\site-packages\h5py\_hl\files.py", line 585, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | ~h5f.OBJ_FILE)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 360, in h5py.h5f.FileID._close_open_objects
OSError: [Errno 28] Driver write request failed (file write failed: time = Tue Sep 19 18:46:15 2023
, filename = 'D:\kartik\091923braintest\NA\cfos-AF647_autofluorescence488\2023-09-19\Cell_001\CH00_000000.h5', file descriptor = 4, errno = 28, error message = 'No space left on device', buf = 00000195AF3CA708, total write size = 4096, bytes this sub-write = 4096, bytes actually written = 18446744073709551615, offset = 146628793136)
camera thread exception happened!  Traceback (most recent call last):
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\multiprocessing\connection.py", line 317, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dean-lab\desktop\aslm\src\aslm\controller\thread_pool.py", line 175, in func
    target(*args, **kwargs)
  File "c:\users\dean-lab\desktop\aslm\src\aslm\controller\controller.py", line 821, in capture_image
    image_id = self.show_img_pipe.recv()
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\multiprocessing\connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\multiprocessing\connection.py", line 326, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dean-lab\desktop\aslm\src\aslm\controller\thread_pool.py", line 64, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\dean-lab\desktop\aslm\src\aslm\controller\thread_pool.py", line 183, in func
    logger.debug(
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\logging\__init__.py", line 1434, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\logging\__init__.py", line 948, in handle
    rv = self.filter(record)
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\logging\__init__.py", line 806, in filter
    result = f.filter(record)
  File "c:\users\dean-lab\desktop\aslm\src\aslm\log_files\filters.py", line 81, in filter
    if record.getMessage().startswith("Performance"):
  File "C:\Users\Dean-Lab\miniconda3\envs\ASLM\lib\logging\__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

### PR DESCRIPTION
**Pull request by AdvancedImagingUTSW**
Ran into different problems for each of our image saving formats (TIFF, OME-TIFF, HDF5, N5).

To circumvent all of these errors, some of which did not percolate up in a fashion that allowed us to handle them with try/except statements, now put a hard stop on the acquisition if the anticipated file format is larger than the disk space available. Message is passed from the model to the controller, and a GUI dialog pops up to inform the user of the problem.

One unique observation is that the N5 file size did not match the actual file size. After some investigation, the N5/Zarr library automatically implemented blosc compression. 

Also added a bunch of numpydocs so that our Sphinx documentation continue to improve.

image

### CODE REVIEW

**Comment by AdvancedImagingUTSW** [comment]
I think we can proceed with this. It prevents deeper problems which are more difficult to address from arising. If it considered too aggressive, I could implement a messagebox that warns the user and asks if they want to continue at their own risk, but this will be more involved.

**Comment by AdvancedImagingUTSW** [comment]
Let me know what you prefer @zacsimile. 

Should we want the option to have the user proceed with the acquisition after being warned, I would do `tkinter.messagebox.askyesno` popup. The popup would be triggered by passing a message to the controller, which would make the message box top-level. The model would have to go into a waiting loop while the user interacts with the message box. Then, depending on what the user inputs, we would have to pass the result back from the controller to the model and ultimately the image writer object to break the waiting loop.

**Comment by zacsimile** [comment]
I think we only need the message box if this commit prevents us from acquiring data in cases where there is sufficient free space. If this PR works on two different microscopes, I think we're clear to merge. Also need to fix a failing test on the Sutter filter wheel.

**Comment by AdvancedImagingUTSW** [comment]
I'll fix the test. We can test it out on CT-ASLM-V1, V2, and BT-MesoSPIM.

**Review by JinlongL — APPROVED** [review]
Tested on ctASLMv1, ctASLMv2 and BT-mesoSPIM by trying to save data on a flash drive with only 537 MB free space. ASLM software perfectly detected there were not enough disk space and acquisition was terminated before even started. 
IMG_7947

**Pull request merged**
