### PR TITLE
display the latest frame

### PR DESCRIPTION
**Pull request by annie-xd-wang**
The GUI will display the latest frame from the camera if it has completed showing one.

### CODE REVIEW

**Comment by zacsimile** [comment]
This works well except if I have more than one channel selected and they have different exposure times. 

[model_debug.log](https://github.com/TheDeanLab/ASLM/files/12114865/model_debug.log)

**Comment by annie-xd-wang** [comment]
The errors shown in the log file are not caused by the changes in this PR. Does the same error happen when you run multiple channels with the develop branch? I can look into the error when working with a device tomorrow.

**Comment by zacsimile** [comment]
You are right, the same error occurs on develop. I hadn't tried this in a while. I will make a new issue.

**Comment by zacsimile** [comment]
This is actually a known error I thought I'd addressed in #508.

**Review by zacsimile — APPROVED** [review]

**Pull request merged**
