### PR TITLE
small issues discovered while I was trying to work with a validated s...

### PR DESCRIPTION
**Pull request by 3vwylie**
…pinbox

"w" -> "write" in trace_add()

tk.DoubleVar -> tk.DoubleVar()

### CODE REVIEW

**Comment by AdvancedImagingUTSW** [comment]
@3vwylie, what did you do with the GUI to throw the error that you found? I would like to test it out...

**Comment by 3vwylie** [comment]
> @3vwylie, what did you do with the GUI to throw the error that you found? I would like to test it out...

I was trying validatedspinboxinstance.variable.get without having a textvariable as a *kwarg. In ASLM, all the other validated spinbox instances that I could find were given a textvariable, so the other side of the "or" was never previously reached. Instead of creating a new doublevar, the code seemed previously to set the variable as the tkinter class for doublevar.... This is approximately the code I was using before I made the changes.  I expected myvar and spinJ1.variable to look similar, which is why I print statemented them.

        spinJ1 = validation.ValidatedSpinbox(
            frm_2,
            from_=0,
            to=25,
            increment=1,
            width=6,
            )
        myvar = tk.DoubleVar()
        print(myvar, spinJ1.variable)

**Comment by 3vwylie** [comment]
I thought that I put an image as part of my pull request comment but I guess not :(

**Comment by AdvancedImagingUTSW** [comment]
Confirmed. If the text variable is not specified, then the validated spinbox will try to assign it as a doubleVar, as @3vwylie showed. However, because this lacks the (), you won't be able to retrieve the variable with a .get call. Now fixed. Thanks.

**Review by AdvancedImagingUTSW — APPROVED** [review]

**Pull request merged**
