### PR TITLE
Update validation.py

### LINKED ISSUE #599: Galvo entry in waveform popup flummoxed by `.`
```
2023-08-22 14:40:41,166 - model - ERROR - galvo_base: could not convert string to float: '.' waveform constants.yml doesn't have parameter amplitude/offset/frequency for Galvo 0
2023-08-22 14:40:41,186 - model - DEBUG - feature_container: running signal node: PrepareNextChannel
2023-08-22 14:40:41,202 - model - DEBUG - filter_wheel_sutter: SutterFilterWheel - Moving to Position 0
2023-08-22 14:40:41,337 - model - DEBUG - feature_container: SignalContainer - Traceback (most recent call last):
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\feature_container.py", line 208, in run
    result, is_end = self.curr_node.run(*args, wait_response=wait_response)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\feature_container.py", line 96, in run
    result = self.node_funcs["main"](*args)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\features\common_features.py", line 167, in signal_func
    self.model.active_microscope.prepare_next_channel()
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\microscope.py", line 531, in prepare_next_channel
    self.daq.prepare_acquisition(channel_key, self.current_exposure_time)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\devices\daq\daq_ni.py", line 397, in prepare_acquisition
    self.create_analog_output_tasks(channel_key)
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\devices\daq\daq_ni.py", line 365, in create_analog_output_tasks
    [
  File "c:\users\deanlab\desktop\github\aslm\src\aslm\model\devices\daq\daq_ni.py", line 366, in <listcomp>
    v["waveform"][channel_key][:max_sample]
TypeError: 'NoneType' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by AdvancedImagingUTSW**
Easy.

### CODE REVIEW

**Comment by zacsimile** [comment]
Works for `.`. Still throws an error for `-`. I think `0.0` is reasonable, but we may consider just reverting to the last valid value instead. May prevent unwanted movement. What do you think?

**Comment by AdvancedImagingUTSW** [comment]
@zacsimile - where are you putting the `-` in? I can't seem to do this on my computer.

**Comment by zacsimile** [comment]
image

**Comment by AdvancedImagingUTSW** [comment]
Is this on your Mac, or a Windows machine? I can't seem to enter a - in the box, at least in the synthetic mode on a Mac...

**Comment by zacsimile** [comment]
This is Mac synthetic mode for me.

**Review by zacsimile — APPROVED** [review]

**Pull request merged**
