### PR TITLE
Add photometrics camera

### PR DESCRIPTION
**Pull request by JinlongL**

### CODE REVIEW

**Comment by zacsimile** [comment]
Confirmed tested on Jinlong's scope.

**Review by AdvancedImagingUTSW — APPROVED** [review]
So long as any problems are isolated to @JinlongL or Reto's microscopes, we can deal with them there.

**Comment by AdvancedImagingUTSW** [comment]
Interestingly, the pvcam python module comes with unit tests, which are being run by GitHub. If we flag these as hardware, we should probably be okay.

**Comment by zacsimile** [comment]
Good call. Updated.

**Pull request merged**
